apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-get-image-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontend-container
        image: gcr.io/ac295-data-science-289403/frontend:webfe
        imagePullPolicy: Always
        env:
        - name: SOCIALDISTANCING_HOST
          valueFrom:
              configMapKeyRef:
                  name: socialdistancing-webappdb-configmap # 🍔
                  key: database_host
        - name: MASKDETECTION_HOST
          valueFrom:
              configMapKeyRef:
                  name: maskdetection-webappdb-configmap # 🍕
                  key: database_host
        ports:
        - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
    name: webapp-frontend-service
spec:
    selector:
        app: frontend-app
    type: NodePort
    ports:
      - protocol: TCP
        port: 8081
        targetPort: 8081
        nodePort: 30000