apiVersion: apps/v1
kind: Deployment
metadata:
  name: maskdetection-webapp-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maskdetection-db-app
  template:
    metadata:
      labels:
        app: maskdetection-db-app
    spec:
      containers:
      - name: maskdetection-db-container
        image: gcr.io/ac295-data-science-289403/maskdetection_webapp:db
        imagePullPolicy: Always
        ports:
        - containerPort: 8083

---
apiVersion: v1
kind: Service
metadata:
    name: maskdetection-webapp-db-service # 🍗
spec:
    selector:
        app: maskdetection-db-app
    ports:
      - protocol: TCP
        port: 8083
        targetPort: 8083